version: '3.4'

volumes: 
  data:
  node_modules:
  __sapper__:
  yarn-cache:

services:
  #  redis:
  #  image: redis:alpine
  #  container_name: local-redis
  #  expose:
  #    - 6379
  #  ports:
  #    - "6379:6379"
  web:
    image: node
    network_mode: host
    volumes:
      - ../node-fridge-logger:/data
      - .:/app
      - node_modules:/app/node_modules
      - __sapper__:/app/__sapper__
      - 'yarn-cache:/usr/local/share/.cache/yarn/'
    # ports: 
    #  - "3000:3000"
    command: sh -c "cd app; yarn; yarn run dev"
    environment:
      DATA_PATH: /data
      # REDIS_SERVER: local-redis
      # REDIS_SERVER: host.docker.internal

